version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      MSSQL_SA_PASSWORD: "Batatinha123"
      ACCEPT_EULA: 1
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - mynw


  contatosapi:
    image: ${DOCKER_REGISTRY-}contatosapi
    ports:
      - 8080:8080
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: Contatos.API/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - mynw


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - mynw


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynw
  
networks:
  mynw: