@Contatos_HostAddress = https://localhost:7225
GET {{Contatos_HostAddress}}/contatos/
Accept: application/json

###

GET {{Contatos_HostAddress}}/contatos/0
Accept: application/json

###

POST {{Contatos_HostAddress}}/contatos
Accept: application/json
Content-Type: application/json

{
  "nome": "Contato 1",
  "ddd": "31",
  "telefone": "9935-83291",
  "email":  "contato1@email.com.br"
}

###

PUT {{Contatos_HostAddress}}/contatos/2
Accept: application/json
Content-Type: application/json

{
  "nome": "Teste 1",
  "telefone": "431434",
  "email": "sdfasdfasdf"
}

###

DELETE {{Contatos_HostAddress}}/contatos/3

###
