@Contatos_HostAddress = https://localhost:7225
GET {{Contatos_HostAddress}}/contatos/
Accept: application/json

###

GET {{Contatos_HostAddress}}/contatos/0
Accept: application/json

###

POST {{Contatos_HostAddress}}/contatos
Accept: application/json
Content-Type: application/json

{
  "nome": "Contato de Teste 2",
  "telefone": "380992323",
  "email":  "contato2@email.com.br",
  "IdRegiao": 3
}

###

PUT {{Contatos_HostAddress}}/contatos/3009
Accept: application/json
Content-Type: application/json

{
  "nome": "Contato de Teste 2",
  "telefone": "380992323",
  "email":  "contato2@email.com.br",
  "IdRegiao": 39
}

###

DELETE {{Contatos_HostAddress}}/contatos/3

###
