@Contatos_HostAddress = https://localhost:7225
GET {{Contatos_HostAddress}}/contatos/
Accept: application/json

###

GET {{Contatos_HostAddress}}/contatos/0
Accept: application/json

###

POST {{Contatos_HostAddress}}/contatos
Accept: application/json
Content-Type: application/json

{
  "nome": "Contato de Teste 3",
  "telefone": "31343144",
  "email":  "contato3@email.com.br",
  "idRegiao": 6
}

###

PUT {{Contatos_HostAddress}}/contatos/4003
Accept: application/json
Content-Type: application/json

{
  "nome": "Contato de Teste 3",
  "telefone": "380992323",
  "email":  "contato2@email.com.br",
  "IdRegiao": 10
}

###

DELETE {{Contatos_HostAddress}}/contatos/3

###
