name: Build and Publish

on:
  workflow_dispatch:
  # push:
     #branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   
   
    - uses: docker/build-push-action@v6.4.1
      with:
        push: false
        tags: user/app:latest
        secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
